// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetConnectionStatus():Promise<main.ConnectionStatus>;

export function GetStatus():Promise<main.StatusInfo>;

export function Login(arg1:string,arg2:string):Promise<main.LoginResult>;

export function Logout():Promise<void>;
